#!/bin/bash
if [ -z $1 ]; then
    echo "usage: $0 [-operation] [prefix1 [prefix2 ...]]"
    echo 'Clear the file of temp data'
    echo 'operation:'
    echo '-a clear all files'
    echo '-p clear files which generated by preprocessing'
    echo '-c clear files which generated by encoding'
    echo '-s clear files which generated by svm'
    exit 1
fi
if [ "$1" = '-a' ]; then
    echo $1
elif [ "$1" = '-p' ]; then
    argv=("$@")
    echo ${argv[@]}
elif [ "$1" = '-c' ]; then
    argv=("$@")
    echo ${argv[@]}
elif [ "$1" = '-s' ]; then
    argv=("$@")
    echo ${argv[@]}
fi